
>P1;1FX8
structureX:1FX8:6    :A:259  :A:unknown:unknown:-1.00:-1.00
---------T-LKGQCIAEFLGTGLLIFFGVGCVAALKVA------------------------------GASFG
QWEISVIWGLGVAMAIYLTAGVSGAHLNPAVTIALWLF-ACFDKRKVIPFIVSQVAGAFCAAALVYGLYY-NLF-
FDFE----QTHHIVRGSVESVDLA-GTFSTYPNPHI-NFVQAFAVEMVITAILMGLILALT-D--DG--NGVPR-
GPLAPLLIGLLIAVIGASMGPLTGFAMNPARDFGPKVFAWLAGW-GNVAFTGGRDIPYFLVPLFGPIVGAIVGAF
AYRKL-IG---------------RHL*

>P1;1J4N
structureX:1J4N:1    :A:249  :A:unknown:unknown:-1.00:-1.00
--MASEFKKKLFWRAVVAEFLAMILFIFISIGSALGF-HY--PIKSNQTTG-----------AV-----Q----D
NVKVSLAFGLSIATLAQSVGHISGAHLNPAVTLGLLLSC-QISVLRAIMYIIAQCVGAIVATAILSGITS-S-L-
---PDN-----------------SL-G-LNALAPGVN-SGQGLGIEIIGTLQLVLCVLATT-DRR-R-R--DLGG
--SGPLAIGFSVALGHLLAIDYTGCGINPARSFGSSVITH--------NFQ------DHWIFWVGPFIGAALAVL
IYDFIL-APRSSDLTDRVKVWTS---*

>P1;2F2B
structureX:2F2B:1    :A:245  :A:unknown:unknown:-1.00:-1.00
MV-------S-LTKRCIAEFIGTFILVFFGAGSAAVTLMIAS-------GGTSPNPFNIGIG-LLGGLG-----D
WVAIGLAFGFAIAASIYALGNISGCHINPAVTIGLWSVKK-FPGREVVPYIIAQLLGAAFGSFIFLQCAGI--GA
-----ATV--------------GGL-G-ATAPFPGI-SYWQAMLAEVVGTFLLMITIMGIAVDE--RA----P--
KGFAGIIIGLTVAGIITTLGNISGSSLNPARTFGPYLNDMIFAGT-D-LW------NYYSIYVIGPIVGAVLAAL
TYQYL--TS-----------------*

>P1;Q9FXW2
sequence:Q9FXW2:38   : :273  : :::-1.00:-1.00
-WMPPSITNAGILQKVGAELISTYILVFAGCGAAMVDEKS------------------------------GGAIT
HFGVSAAFGLVVMIMIYSVGHISGAHMNPAVTLAFATV-RHFPWAQVPAYIGAQVVAAISAAFSLRLILG---GA
--------------------------AKIGATLP-VGSDVQSLALEVITSYILMFVVSAVATDT--------RAI
GELAGLAVGSAVALDAIFAGPICGASMNPARSIGPAVASY--------DFK------SLWVYIVGPILGCLLGAW
SYTMIKLPEQPQDLAMISQS------*
